import { JWT_REFRESH_EXPIRES_IN, JWT_ACCESS_EXPIRES_IN } from "./env.js";

export const REFRESH_EXP_DAYS = JWT_REFRESH_EXPIRES_IN + "d"
export const REFRESH_EXP_MS = parseInt(JWT_REFRESH_EXPIRES_IN) * 24 * 60 * 60 * 1000;
export const ACCESS_EXP_MINUTES = JWT_ACCESS_EXPIRES_IN + "m"
export const SESSION_EXPIRES_DAYS = parseInt(JWT_REFRESH_EXPIRES_IN)